version: "3.8"
services:
  react-app:
    image: react-app
    build:
      context: ./
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - gb-bridge-network
networks:
  gb-bridge-network:
    external: true
