version: "3.8"
services:
  db:
    image: mysql:8
    container_name: gb_mysql_database_container
    environment:
     - MYSQL_ROOT_PASSWORD=changeMe
     - MYSQL_DATABASE=customer_pref 
     - MYSQL_USER=cp
     - MYSQL_PASSWORD=changeMeCp
    
    ports:
      - 3306:3306
    volumes:
      - mysql1:/var/lib/mysql
    networks:
      - gb-bridge-network

volumes:
  mysql1:

networks:
  gb-bridge-network:
    external: true